// <auto-generated />
using AmsAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmsAPI.Migrations
{
    [DbContext(typeof(AssociateMasterContext))]
    [Migration("20210820185403_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmsAPI.Models.AssociatesMaster", b =>
                {
                    b.Property<int>("AssociateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssociateName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("AssociateId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("AssociatesMasters");
                });

            modelBuilder.Entity("AmsAPI.Models.SpecializationMaster", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SpecializationName")
                        .HasColumnType("varchar(250)");

                    b.HasKey("SpecializationId");

                    b.ToTable("SpecializationMasters");
                });

            modelBuilder.Entity("AmsAPI.Models.AssociatesMaster", b =>
                {
                    b.HasOne("AmsAPI.Models.SpecializationMaster", "SpecializationMaster")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecializationMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
